#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x89EFD588E975D6DF (rbtcollins@hp.com)
#
Name     : testrepository
Version  : 0.0.20
Release  : 27
URL      : http://pypi.debian.net/testrepository/testrepository-0.0.20.tar.gz
Source0  : http://pypi.debian.net/testrepository/testrepository-0.0.20.tar.gz
Source99 : http://pypi.debian.net/testrepository/testrepository-0.0.20.tar.gz.asc
Summary  : A repository of test results.
Group    : Development/Tools
License  : Apache-2.0
Requires: testrepository-bin
Requires: testrepository-legacypython
Requires: testrepository-python3
Requires: testrepository-python
Requires: fixtures
Requires: python-subunit
Requires: pytz
Requires: testresources
Requires: testscenarios
Requires: testtools
BuildRequires : extras
BuildRequires : fixtures
BuildRequires : linecache2
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mimeparse
BuildRequires : python-subunit
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : traceback2
BuildRequires : unittest2

%description
+++++++++++++++
        
        Overview
        ~~~~~~~~
        
        This project provides a database of test results which can be used as part of

%package bin
Summary: bin components for the testrepository package.
Group: Binaries

%description bin
bin components for the testrepository package.


%package legacypython
Summary: legacypython components for the testrepository package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the testrepository package.


%package python
Summary: python components for the testrepository package.
Group: Default
Requires: testrepository-legacypython
Requires: testrepository-python3

%description python
python components for the testrepository package.


%package python3
Summary: python3 components for the testrepository package.
Group: Default
Requires: python3-core

%description python3
python3 components for the testrepository package.


%prep
%setup -q -n testrepository-0.0.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507179834
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test || :
%install
export SOURCE_DATE_EPOCH=1507179834
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/testr

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
