#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : testrepository
Version  : 0.0.19
Release  : 7
URL      : https://github.com/testing-cabal/testrepository/archive/0.0.19.tar.gz
Source0  : https://github.com/testing-cabal/testrepository/archive/0.0.19.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: testrepository-bin
Requires: testrepository-python
BuildRequires : extras
BuildRequires : fixtures
BuildRequires : linecache2
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mimeparse
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : traceback2
BuildRequires : unittest2

%description
Test Repository
+++++++++++++++
Overview
~~~~~~~~
This project provides a database of test results which can be used as part of
developer workflow to ensure/check things like:

%package bin
Summary: bin components for the testrepository package.
Group: Binaries

%description bin
bin components for the testrepository package.


%package python
Summary: python components for the testrepository package.
Group: Default

%description python
python components for the testrepository package.


%prep
%setup -q -n testrepository-0.0.19

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
py.test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/testr

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
